version: '3.8'

services:
  web:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: rebois_user
      POSTGRES_PASSWORD: rebois_pass
      POSTGRES_DB: rebois_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    depends_on:
      - web

volumes:
  pgdata:
