services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: rebois_user
      POSTGRES_PASSWORD: rebois_pass
      POSTGRES_DB: rebois_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d


volumes:
  pgdata:
