"""set land and project model

Revision ID: 27fde4ca2a6e
Revises: 892b2ae3a2f5
Create Date: 2025-06-12 20:25:58.948817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fde4ca2a6e'
down_revision = '892b2ae3a2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
