"""Create messages table with UUID

Revision ID: 7194b42273f5
Revises: 7404f194a78b
Create Date: 2025-07-10 13:20:32.347395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7194b42273f5'
down_revision = '7404f194a78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sponsor_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tech_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tech_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('tech_rating')
        batch_op.drop_column('tech_report')
        batch_op.drop_column('sponsor_rating')
        batch_op.drop_column('sponsor_report')

    op.drop_table('messages')
    # ### end Alembic commands ###
