"""add the propeties rating and report for both sponsor and tech structure to the project table

Revision ID: 7404f194a78b
Revises: fbe56759c979
Create Date: 2025-07-02 00:01:55.292689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7404f194a78b'
down_revision = 'fbe56759c979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sponsor_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tech_report', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tech_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('tech_rating')
        batch_op.drop_column('tech_report')
        batch_op.drop_column('sponsor_rating')
        batch_op.drop_column('sponsor_report')

    # ### end Alembic commands ###
