"""add 2FAcode table

Revision ID: 892b2ae3a2f5
Revises: 
Create Date: 2025-06-11 16:27:19.794675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892b2ae3a2f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_fa_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('two_fa_codes')
    # ### end Alembic commands ###
